# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2be90e30-be49-4a3d-b1c0-a19a2633b802'

  # Function app name
  functionAppName: 'Weario-Connections'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/Weario.Integration.Functions.PWW'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(functionAppName)
            # To deploy the settings on a slot, provide slot name as below. By default, the settings would be applied to the actual Web App (Production slot)
            # slotName: staging
              appSettings: |
                [
                  {
                    "name": "NAME",
                    "value": "Rick",
                    "slotSetting": false
                  },
                  {
                    "name": "Title",
                    "value": "Esteemed",
                    "slotSetting": false
                  },
                  {
                    "name": "Interests:NumberOneHobby",
                    "value": "Not cats",
                    "slotSetting": false
                  },
                  {
                    "name": "Test",
                    "value": "Can I change this in app settings?",
                    "slotSetting": false
                  }
                ]
              generalSettings: |
                [
                  {
                    "name": "NAME",
                    "value": "test 2",
                    "slotSetting": false
                  },
                  {
                    "name": "Test",
                    "value": "Can I change this in general settings?",
                    "slotSetting": false
                  }
                ]
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              appSettings: '-Test "Should be this now in app settings"'
              configurationStrings: '-Test "Should be this now in configuration settings"'